In [1]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../src/afterFeatureEngineering_data.csv")
data.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,linkedin_connections,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,184,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,539,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,568,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,550,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,833,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed

In [3]:
x = data.drop(columns=['placement_status'])
x.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,github_repos,linkedin_connections,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,1,184,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,2,539,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,2,568,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,1,550,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,4,833,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4

In [4]:
y = data['placement_status']
y.head()

0    Not Placed
1    Not Placed
2        Placed
3    Not Placed
4        Placed
Name: placement_status, dtype: str

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)
# print("training set of x :",x_train)
# print("training set of y :",y_train)
# print("testing set of x :",x_test)
# print("testing set of y :",x_test)

In [6]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(80000, 24)
(20000, 24)
(80000,)
(20000,)

In [7]:
x_train.to_csv("../src/x_train.csv",index=False)
y_train.to_csv("../src/y_train.csv",index=False)
x_test.to_csv("../src/x_test.csv",index=False)
y_test.to_csv("../src/y_test.csv",index=False)