In [1]:
import pandas as pd
import numpy as np

In [2]:
import sys
sys.path.append("..")
from src.load_data import load_data
data = load_data()
data.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16

Removing salary_package_lpa feature because it leaks information. Students who are not placed usually have 0 LPA, making it a target-derived feature.

In [3]:
data = data.drop(columns=['salary_package_lpa'])
data.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,linkedin_connections,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,184,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,539,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,568,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,550,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,833,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed

Encoding the target value - placement_status using LabelEncoder

In [5]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['placement_status'] = le.fit_transform(data['placement_status'])
data.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,linkedin_connections,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,184,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,0
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,539,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,0
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,568,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,1
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,550,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,0
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,833,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,1

In [6]:
data.to_csv("../src/afterFeatureEngineering_data.csv",index=False)